worker_processes auto;
events { worker_connections 1024; }

http {
  server_tokens off;
  limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/s;

  upstream app {
    server app1:80 max_fails=3 fail_timeout=10s;
    server app2:80 max_fails=3 fail_timeout=10s;
    keepalive 16;
  }

  include /etc/nginx/conf.d/*.conf;
}
